services:
  #/* ----------------------------- Message Broker ----------------------------- */
  msg_broker:
    image: "nats:latest"
    container_name: nats
    ports:
      - 1742:4222
      - 1722:8222
    command: -c /tmp/nats/config/nats.cfg
    env_file:
      - .env.nats
    volumes:
      - ./nats_data:/tmp/nats/jetstream
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.2
    profiles: [nats]
  #/* -------------------------------------------------------------------------- */

  #/* ------------------------ API REST / USP Controller ----------------------- */
  controller:
    image: "oktopusp/controller"
    container_name: controller
    ports:
      - 1700:8000
    depends_on:
      - mongo_usp
    env_file:
      - .env.controller
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.3
    profiles: [controller]
  #/* -------------------------------------------------------------------------- */

  #/* ---------------------------- Databases / Cache --------------------------- */
  mongo_usp:
    image: mongo
    container_name: mongo_usp
    ports:
      - 27017:27017
    networks:
      usp_network:
        ipv4_address: 172.16.235.4
    volumes:
      - ./mongo_data:/data/db
    profiles: [controller, adapter]

  #/* -------------------------------------------------------------------------- */

  #/* ----------------------- Message Transfer Protocols ----------------------- */
  mqtt:
    image: "oktopusp/mqtt"
    container_name: mqtt
    ports:
      - 1718:1883
      - 1783:8883
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.6
    profiles: [mqtt]

  ws:
    image: "oktopusp/ws"
    container_name: websockets
    ports:
      - 1788:8080
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.7
    profiles: [ws]

  stomp:
    image: "oktopusp/stomp"
    container_name: stomp
    ports:
      - 17616:61613
    networks:
      usp_network:
        ipv4_address: 172.16.235.8
    profiles: [stomp]
  #/* -------------------------------------------------------------------------- */

  #/* --------------- Message transfer Protocols Adapters to NATS -------------- */
  mqtt-adapter:
    image: "oktopusp/mqtt-adapter"
    container_name: mqtt-adapter
    depends_on:
      - mqtt
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.9
    profiles: [mqtt]

  ws-adapter:
    image: "oktopusp/ws-adapter"
    container_name: ws-adapter
    depends_on:
      - ws
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.10
    profiles: [ws]

  stomp-adapter:
    image: "oktopusp/stomp-adapter"
    container_name: stomp-adapter
    depends_on:
      - stomp
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.11
    profiles: [stomp]

  adapter:
    image: "oktopusp/adapter"
    container_name: adapter
    depends_on:
      - mongo_usp
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.12
    profiles: [adapter]
  #/* -------------------------------------------------------------------------- */

  #/* ------------- SocketIO Real Time Communication With Frontend ------------- */
  socketio:
    image: "oktopusp/socketio"
    container_name: socketio
    ports:
      - 1750:5000
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.13
    profiles: [frontend]
  #/* -------------------------------------------------------------------------- */

  #/* -------------------------------- Frontend -------------------------------- */
  frontend:
    image: "oktopusp/frontend"
    container_name: frontend
    ports:
      - 1730:3000
    networks:
      usp_network:
        ipv4_address: 172.16.235.14
    profiles: [frontend]
  #/* -------------------------------------------------------------------------- */


  acs:
    image: "oktopusp/acs"
    container_name: acs
    ports:
      - 9292:9292
    env_file:
      - .env.all
    volumes:
      - ./nats_config:/tmp/nats/config
    networks:
      usp_network:
        ipv4_address: 172.16.235.16
    profiles: [cwmp]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 1780:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      usp_network:
        ipv4_address: 172.16.235.17

  file-server:
    image: oktopusp/file-server
    container_name: file-server
    ports:
      - 1704:8004
    volumes:
      - ./firmwares:/app/firmwares
      - ./images:/app/images
    env_file:
      - .env.all
    networks:
      usp_network:
        ipv4_address: 172.16.235.18

networks:
  usp_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.235.0/24
          gateway: 172.16.235.1
